sudo: required
services:
  - docker

before_install:
  - docker build -t xulq/docker-complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true xulq/docker-complex-test npm test

after_success:
  - docker build -t xulq/docker-complex-client ./client
  - docker build -t xulq/docker-complex-nginx ./nginx
  - docker build -t xulq/docker-complex-server ./server
  - docker build -t xulq/docker-complex-worker ./worker
  - echo "$DOCKER_PASSWORD" |docker login -u "$DOCKER_ID" --password_stdin
  - docker push xulq/docker-complex-client
  - docker push xulq/docker-complex-nginx
  - docker push xulq/docker-complex-server
  - docker push xulq/docker-complex-worker
